In [8]:
import numpy as np
marks = np.array([78, 85, 90, 67, 88, 92, 75, 81, 69, 95])
print("Marks Datatype:",marks.dtype)
print("Marks Array:",marks)
print("size:",marks.size)


Marks Datatype: int64
Marks Array: [78 85 90 67 88 92 75 81 69 95]
size: 10




In [15]:
emps = np.array([101, 102, 103, 104, 105, 106])
print("Employee ids:",emps)
print("Dimensions:",emps.ndim)
print("Shape:",emps.shape)

Employee ids: [101 102 103 104 105 106]
Dimensions: 1
Shape: (6,)


In [20]:
students = np.array([
    [78, 82, 90],
    [65, 70, 88],
    [91, 86, 79]
])
print("Array:",students)
print("Shape:",students.shape)
print("Size:",students.size)
print("Dtype:",students.dtype)

Array: [[78 82 90]
 [65 70 88]
 [91 86 79]]
Shape: (3, 3)
Size: 9
Dtype: int64


In [28]:
zeros=np.zeros((2,2))
print("Zeors:",zeros)
ones=np.ones((5,5))
print("Ones :",ones)
identity = np.eye(6)
print("Identity:",identity)

Zeors: [[0. 0.]
 [0. 0.]]
Ones : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Identity: [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [30]:
full = np.full((3,4),5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [41]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Array:",arr)
print("Size:",arr.size)
print("Dimensions:",arr.ndim)
print("dtype:",arr.dtype)

Array: [[10 20 30]
 [40 50 60]
 [70 80 90]]
Size: 9
Dimensions: 2
dtype: int64
