In [2]:
import numpy as np
#Q1
arr =np.array([10, 20, 30, 40, 50])
print("First element:",arr[0])

10


In [3]:
#Q2
arr1 = np.array([5, 10, 15, 20, 25, 30])
print("last element:",arr1[-1])


last element: 30


In [4]:
#Q3
arr2 = np.array([100, 200, 300, 400, 500])
print("third element:",arr2[2])

third element: 300


In [10]:
#Q4
arr3 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]])
print(arr3[1,1])

50


In [11]:
#Q5
print(arr3[2,2])

90


In [16]:
arr4=np.array([
[[1,2],[3,4]],
[[5,6],[7,8]]
])
print(arr4[1,0,1])

6


In [17]:
#Q6
print(arr4[0,1,0])

3


In [31]:
#Q7
arr5=np.array([10,20,30,40,50,60,70,80])
print(arr5[0:4])
#Q8
print(arr5[2:6])
#Q9
print(arr5[4:])
#Q10
print(arr5[::2])
#Q11
print(arr5[-3:])

[10 20 30 40]
[30 40 50 60]
[50 60 70 80]
[10 30 50 70]
[60 70 80]


In [41]:
#Q12
arr6 = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr6[0])
#Q13
print(arr6[2])
#Q14
print(arr6[:,1])
#Q15
print(arr6[:,2])
#Q16
print(arr6[0:2])
#Q17
print(arr6[:,0:2])
#Q18
print(arr6[:2,:2])

[10 20 30]
[70 80 90]
[20 50 80]
[30 60 90]
[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]
 [70 80]]
[[10 20]
 [40 50]]
